version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: 'app'
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "../app/back-end:/var/www/html"
    links:
      - php
  php:
    build: php
    volumes:
      - "../app/back-end:/var/www/html"
  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./pgsql/db.env
    volumes:
      - ../db-data:/var/lib/postgresql/data
  vue:
    build:
      context: ../app/front-end
      dockerfile: docker/Dockerfile
    container_name: vue
    volumes:
      - "../app/front-end:/var/www/app"
    ports:
      - "80:80"